go get "github.com/apsdehal/go-logger"
go get "github.com/prometheus/client_golang/prometheus"
go get "github.com/prometheus/client_golang/prometheus/promhttp"
go get "gopkg.in/yaml.v2"
go get "gopkg.in/alecthomas/kingpin.v2"
go get "github.com/sirupsen/logrus"
